Repository w3f/polkadot-wiki, pull requests merged in 2020-07, with the labels that each got.

#641 New ribbon
  website/i18n/en.json
  website/siteConfig.js
  website/static/404.html
  website/static/css/custom.css
  website/static/index.html
  website/static/js/custom.js
Labels: A0 - Please Review

#640 Add guides page
  docs/getting-started.md
  website/i18n/en.json
  website/sidebars.json
Labels: A0 - Please Review

#682 Added Algolia API key and index name, closes #675
  kusama-guide/siteConfig.js
Labels: T5 - Admin

#683 Add section about unique transaction identifiers
  docs/build-protocol-info.md
  website/i18n/en.json
Labels: A0 - Please Review, K1 - Infrastructure

#635 Add section on multisig deposits
  docs/learn-accounts.md
Labels: A0 - Please Review

#694 Add docusaurus patch for injection
  package.json
  patches/docusaurus+1.14.4.patch
  scripts/inject.js
  yarn.lock
Labels: A2 - Insubstantial, T5 - Admin

#705 Kusama Getting Started Page
  docs/kusama-getting-started.md
  kusama-guide/sidebars.json
  kusama-guide/siteConfig.js
Labels: A0 - Please Review

#697 Add Transactions instructions, clean up getting started page
  docs/assets/Send-Transaction.png
  docs/assets/Send-Transfer.png
  docs/getting-started.md
  docs/learn-transactions.md
  website/sidebars.json
  website/siteConfig.js
  website/static/index.html
Labels: A0 - Please Review

#711 More details in Polkadots Intro
  docs/learn-introduction.md
  docs/maintain-wss.md
Labels: A0 - Please Review
