Repository w3f/polkadot-wiki, pull requests merged in 2020-03, with the labels that each got.

#317 Change exchange to wallet
  docs/build-exchange-integration.md
  docs/build-index.md
  website/i18n/en.json
  website/sidebars.json
Labels: documentation

#324 Add integration guide
  docs/build-exchange-integration.md
  docs/build-index.md
  docs/build-node-interaction.md
  docs/build-node-management.md
  docs/build-protocol-info.md
  docs/build-tools-index.md
  docs/build-transaction-construction.md
  docs/maintain-guides-how-to-setup-sentry-node.md
  docs/maintain-guides-how-to-use-polkadot-secure-validator.md
  website/i18n/en.json
  website/sidebars.json
Labels: documentation, ready for review

#335 Add vesting info
  docs/learn-DOT.md
  docs/maintain-guides-how-to-validate-kusama.md
  docs/mirror-build-build-with-polkadot.md
  docs/mirror-maintain-guides-how-to-validate-kusama.md
Labels: ready for review
