Repository w3f/polkadot-wiki, pull requests merged in 2020-09, with the labels that each got.

#887 Add Vanity generator to Wiki
  docs/assets/polkadot_save_account.png
  docs/assets/polkadot_vanity_generate.png
  docs/assets/polkadot_vanity_generator_page.png
  docs/learn-account-generation.md
Labels: A0 - Please Review

#849 Proxy generation and remove section
  docs/assets/multisig_proxy_diagram.png
  docs/assets/polkadot_add_another_proxy.png
  docs/assets/polkadot_adding_proxies.png
  docs/assets/polkadot_anon_proxy.png
  docs/assets/polkadot_anonymous_proxy.png
  docs/assets/polkadot_generating_proxy.png
  docs/assets/polkadot_multisig_anon.png
  docs/assets/polkadot_regular_proxies.png
  docs/assets/polkadot_remove_proxy.png
  docs/assets/proxy_anonymous_diagram.png
  docs/assets/regular_proxy_diagram.png
  docs/learn-proxies.md
Labels: A0 - Please Review

#889 Add cover page to integration guide
  docs/build-index.md
  docs/build-integration.md
  docs/build-node-interaction.md
  docs/build-node-management.md
  docs/build-protocol-info.md
  website/i18n/en.json
  website/sidebars.json
Labels: A0 - Please Review, K0 - Intro Material

#895 Add links to Knowledge Base
  docs/getting-started.md
  docs/maintain-errors.md
Labels: A0 - Please Review

#781 Node Monitoring Setup
  docs/assets/guides/how-to-monitor/1-alert-manager.png
  docs/assets/guides/how-to-monitor/1-grafana-login.png
  docs/assets/guides/how-to-monitor/2-add-data-source-2.png
  docs/assets/guides/how-to-monitor/2-add-data-source.png
  docs/assets/guides/how-to-monitor/2-alert-manager.png
  docs/assets/guides/how-to-monitor/3-alert-manager.png
  docs/assets/guides/how-to-monitor/3-select-prometheus.png
  docs/assets/guides/how-to-monitor/4-alert-manager.png
  docs/assets/guides/how-to-monitor/4-configure-data-source.png
  docs/assets/guides/how-to-monitor/5-alert-manager.png
  docs/assets/guides/how-to-monitor/5-import-dashboard-2.png
  docs/assets/guides/how-to-monitor/5-import-dashboard.png
  docs/assets/guides/how-to-monitor/6-alert-manager.png
  docs/assets/guides/how-to-monitor/6-dashboard-metric.png
  docs/maintain-guides-how-to-monitor-your-node.md
  website/i18n/en.json
  website/sidebars.json
Labels: A0 - Please Review

#902 Add "injected" term to glossary
  docs/glossary.md
Labels: A0 - Please Review

#900 Update staking info
  docs/glossary.md
  docs/learn-nominator.md
  docs/learn-staking.md
Labels: A0 - Please Review

#881 Update all Photos/Instructions on Kusama Guide
  docs/assets/kusama/kusama_add_account.png
  docs/assets/kusama/kusama_backup_account.png
  docs/assets/kusama/kusama_copy_address.png
  docs/assets/kusama/kusama_create_account.png
  docs/assets/kusama/kusama_make_account_initial.png
  docs/assets/kusama/kusama_make_account_recoverable.png
  docs/assets/kusama/kusama_make_recoverable.png
  docs/assets/kusama/kusama_polkadotjs_add_account.png
  docs/assets/kusama/kusama_social_recovery_accounts_page.png
  docs/assets/kusama/kusama_society_page.png
  docs/assets/kusama/kusama_society_page2.png
  docs/kusama-claims.md
  docs/kusama-endpoints.md
  docs/kusama-social-recovery.md
  docs/maintain-guides-society-kusama.md
  kusama-guide/static/img/endpoints/kusama_endpoint_parity.png
  kusama-guide/static/img/endpoints/kusama_endpoint_web3.png
  kusama-guide/static/img/endpoints/parity.png
  kusama-guide/static/img/endpoints/ryo.png
  kusama-guide/static/img/endpoints/w3f.png
  kusama-guide/static/img/kusama/kusama_polkadotjs_add_account-1.png
  kusama-guide/static/img/kusama/kusama_polkadotjs_create.png
  kusama-guide/static/img/kusama/kusama_polkadotjs_final_account.png
  kusama-guide/static/img/kusama/kusama_polkadotjs_mnemonicseed.jpg
  kusama-guide/static/img/kusama/kusama_polkadotjs_uncheck.png
Labels: A0 - Please Review

#572 Ledger guide
  docs/assets/ledger-2.png
  docs/assets/ledger-3.png
  docs/assets/ledger-4.png
  docs/assets/ledger.png
  docs/kusama-ledger.md
  docs/learn-ledger.md
  kusama-guide/sidebars.json
  website/i18n/en.json
  website/sidebars.json
Labels: A0 - Please Review

#939 Clarify that a burn isn't really a burn in Kusama currently
  docs/kusama-parameters.md
Labels: A0 - Please Review

#940 Closes #882
  kusama-guide/siteConfig.js
  kusama-guide/static/css/copycode.css
  kusama-guide/static/js/clipboard.min.js
  kusama-guide/static/js/copycode.js
  website/siteConfig.js
  website/static/css/copycode.css
  website/static/js/clipboard.min.js
  website/static/js/copycode.js
Labels: A0 - Please Review

#962 Clarified Chromium support
  docs/kusama-ledger.md
  docs/learn-ledger.md
Labels: A0 - Please Review, P2 - ASAP, T3 - Enhancement

#960 Added any payout note
  docs/assets/payout/01.png
  docs/learn-staking.md
  docs/maintain-guides-how-to-nominate-kusama.md
  docs/maintain-guides-how-to-nominate-polkadot.md
  docs/maintain-guides-how-to-validate-kusama.md
  docs/maintain-guides-how-to-validate-polkadot.md
Labels: A0 - Please Review, K0 - Intro Material, P2 - ASAP, Q0 - Easy, T3 - Enhancement

#963 Added ledger info due to recent changes
  docs/assets/ledger/add-account.png
  docs/assets/ledger/query-ledger.png
  docs/kusama-ledger.md
  docs/learn-ledger.md
Labels: A0 - Please Review, P2 - ASAP, T3 - Enhancement

#966 Runtime Version vs Client clarification
  docs/maintain-guides-how-to-nominate-kusama.md
  docs/maintain-guides-how-to-nominate-polkadot.md
  docs/maintain-guides-how-to-validate-kusama.md
  docs/maintain-guides-how-to-validate-polkadot.md
Labels: A0 - Please Review, A2 - Insubstantial, Q0 - Easy, T3 - Enhancement

#983 Fixed sidebar order / next button
  website/sidebars.json
Labels: A0 - Please Review, P2 - ASAP, Q0 - Easy, T5 - Admin

#976 Add information on proxy deposits
  docs/learn-proxies.md
  package.json
  scripts/computed.js
  scripts/inject-dict.json
  scripts/inject.js
Labels: A0 - Please Review

#988 Removed Ledger incompatibility note
  docs/kusama-ledger.md
  docs/learn-ledger.md
Labels: A0 - Please Review, P2 - ASAP, Q0 - Easy

#981 Ledger update
  docs/kusama-ledger.md
  docs/learn-ledger.md
Labels: A0 - Please Review, A2 - Insubstantial, P2 - ASAP

#987 Closes #845
  docs/maintain-guides-how-to-vote-councillor.md
Labels: A0 - Please Review, P2 - ASAP, Q0 - Easy

#973 Added ENS guide
  docs/assets/ens/01-min.png
  docs/assets/ens/02-min.png
  docs/assets/ens/03-min.png
  docs/assets/ens/04-min.png
  docs/assets/ens/05-min.png
  docs/assets/ens/06-min.png
  docs/assets/ens/07-min.png
  docs/assets/ens/08-min.png
  docs/ens.md
  kusama-guide/sidebars.json
  scripts/mirror.js
  website/sidebars.json
Labels: A0 - Please Review, K6 - Advanced/Other, Kusama, P7 - Nice to Have, Q2 - Medium, T2 - New Page

#937 Updating instructions/photos on Kusama Guide
  docs/assets/kusama/kusama_nominator_popup.png
  docs/assets/kusama/kusama_nominator_selection.png
  docs/maintain-guides-how-to-nominate-kusama.md
Labels: A0 - Please Review

#835 Rococo guide
  docs/assets/polkadotjs_network_parachains.png
  docs/assets/rococo/rococo-add-json.png
  docs/assets/rococo/rococo-change-network.png
  docs/assets/rococo/rococo-downward-transfer.png
  docs/assets/rococo/rococo-error-message.png
  docs/assets/rococo/rococo-error.png
  docs/assets/rococo/rococo-fill-out-fields.png
  docs/assets/rococo/rococo-lateral-transfer.png
  docs/assets/rococo/rococo-lateral-transfer2.png
  docs/assets/rococo/rococo-register-parachain.png
  docs/assets/rococo/rococo-two-parachains.png
  docs/assets/rococo/rococo-ui-connected.png
  docs/assets/rococo/rococo-upward-transfer.png
  docs/build-parachains-rococo.md
  website/sidebars.json
Labels: A0 - Please Review

#1031 Closes #999, closes #1017
  docs/assets/accounts/index.png
  docs/learn-account-generation.md
  docs/learn-accounts.md
Labels: A0 - Please Review, K5 - Learn, P2 - ASAP, T3 - Enhancement, stale

#1026 Closes 1025
  docs/learn-collator.md
Labels: A0 - Please Review, Q0 - Easy, T3 - Enhancement, stale

#816 WIP: Created a small section on Polkadot 2.0
  docs/learn-launch.md
Labels: A3 - In Progress

#1030 Closes #1015 and #1029
  docs/learn-governance.md
Labels: A0 - Please Review, K5 - Learn, P2 - ASAP, Q0 - Easy, T3 - Enhancement, stale

#1010 Close #997
  .gitignore
  README.md
  docs/assets/treasury/motion.png
  docs/assets/treasury/proposals.png
  docs/assets/treasury/submit-new.png
  docs/learn-treasury.md
  package.json
  scripts/inject-dict.json
  scripts/inject.js
  scripts/mirror.js
Labels: A0 - Please Review, K5 - Learn, P2 - ASAP, T3 - Enhancement

#739 XCMP animation
  docs/assets/xcmp_animation.mp4
  docs/learn-crosschain.md
  website/i18n/en.json
Labels: A0 - Please Review
