Repository w3f/polkadot-wiki, pull requests merged in 2020-06, with the labels that each got.

#516 Proper use of which and caps on Relay Chain
  docs/build-build-with-polkadot.md
  docs/build-cumulus.md
  docs/build-deploy-parachains.md
  docs/build-examples-index.md
  docs/build-pdk.md
  docs/build-smart-contracts.md
  docs/glossary.md
  docs/kusama-adverserial-cheatsheet.md
  docs/learn-DOT.md
  docs/learn-accounts.md
  docs/learn-architecture.md
  docs/learn-auction.md
  docs/learn-comparison-dfinity.md
  docs/learn-comparisons.md
  docs/learn-consensus.md
  docs/learn-crosschain.md
  docs/learn-faq.md
  docs/learn-governance.md
  docs/learn-identity.md
  docs/learn-implementations.md
  docs/learn-parachains.md
  docs/learn-parathreads.md
  docs/learn-phragmen.md
  docs/learn-randomness.md
  docs/learn-relevant-links.md
  docs/learn-roadmap.md
  docs/learn-security.md
  docs/learn-spree.md
  docs/learn-staking.md
  docs/learn-transaction-fees.md
  docs/learn-treasury.md
  docs/maintain-errors.md
  docs/maintain-guides-democracy.md
  docs/maintain-guides-how-to-join-council.md
  docs/maintain-guides-how-to-nominate-polkadot.md
  docs/maintain-guides-how-to-use-polkadot-secure-validator.md
  docs/maintain-guides-how-to-validate-polkadot.md
  docs/maintain-guides-how-to-vote-councillor.md
  docs/maintain-guides-society-kusama.md
  docs/maintain-guides-validator-payout.md
  docs/maintain-nominator.md
  docs/maintain-sync.md
  docs/maintain-validator.md
Labels: A0 - Please Review, A2 - Insubstantial

#532 Minor integration guide fixes
  docs/build-node-interaction.md
  docs/build-node-management.md
  docs/build-protocol-info.md
Labels: A0 - Please Review, A2 - Insubstantial, K1 - Infrastructure

#551 Add proxies
  docs/assets/proxies-example.png
  docs/learn-accounts.md
  docs/learn-proxies.md
  docs/maintain-guides-democracy.md
  website/i18n/en.json
  website/sidebars.json
Labels: A0 - Please Review, K5 - Learn

#553 an unforgivable grammatical error
  docs/learn-proxies.md
Labels: P0 - Drop everything

#600 Updated FAQ page
  docs/faq.md
  docs/learn-introduction.md
  docs/maintain-guides-how-to-join-council.md
  docs/maintain-guides-how-to-validate-kusama.md
  docs/maintain-guides-how-to-validate-polkadot.md
  docs/maintain-guides-secure-validator.md
  website/sidebars.json
Labels: A0 - Please Review

#593 Created a guide for Restoring Accounts
  docs/assets/accounts/parity_click_restore.jpg
  docs/assets/accounts/parity_enter_password.jpg
  docs/assets/accounts/parity_recovery_phrase.jpg
  docs/assets/accounts/parity_restoring_account.jpg
  docs/assets/accounts/parity_save_recovery.png
  docs/assets/accounts/parity_select_profile.jpeg
  docs/assets/accounts/polkadot.js_enter_password.png
  docs/assets/accounts/polkadot.js_list_accounts.png
  docs/assets/accounts/polkadot.js_restore_account.png
  docs/assets/accounts/polkadot_click_restore.png
  docs/assets/accounts/polkadot_enter_password.png
  docs/assets/accounts/polkadot_restore_account.png
  docs/assets/accounts/polkadot_restore_complete.png
  docs/learn-account-restore.md
  website/sidebars.json
Labels: A0 - Please Review
