Repository w3f/polkadot-wiki, pull requests merged in 2021-07, with the labels that each got.

#2181 Update Validator Pages
  docs/assets/guides/how-to-validate/kusama-dashboard-bonding.png
  docs/assets/guides/how-to-validate/kusama-dashboard-staking.png
  docs/assets/guides/how-to-validate/kusama-dashboard-telemetry.png
  docs/assets/guides/how-to-validate/kusama-dashboard-validate-1.png
  docs/assets/guides/how-to-validate/kusama-dashboard-validate-2.png
  docs/assets/guides/how-to-validate/kusama-set-session-key-1.png
  docs/assets/guides/how-to-validate/kusama-set-session-key-2.png
  docs/assets/guides/how-to-validate/polkadot-authorize-transaction-stash.png
  docs/assets/guides/how-to-validate/polkadot-dashboard-bonding.jpg
  docs/assets/guides/how-to-validate/polkadot-dashboard-bonding.png
  docs/assets/guides/how-to-validate/polkadot-dashboard-staking.jpg
  docs/assets/guides/how-to-validate/polkadot-dashboard-staking.png
  docs/assets/guides/how-to-validate/polkadot-dashboard-telemetry.png
  docs/assets/guides/how-to-validate/polkadot-dashboard-validate-1.png
  docs/assets/guides/how-to-validate/polkadot-dashboard-validate-2.png
  docs/assets/guides/how-to-validate/polkadot-stash-overview.png
  docs/assets/guides/how-to-validate/set-session-key-1.jpg
  docs/assets/guides/how-to-validate/set-session-key-1.png
  docs/assets/guides/how-to-validate/set-session-key-2.jpg
  docs/assets/guides/how-to-validate/set-session-key-2.png
  docs/learn-kusama-vs-polkadot.md
  docs/learn-simple-payouts.md
  docs/learn-validator.md
  docs/maintain-guides-how-to-upgrade.md
  docs/maintain-guides-how-to-validate-kusama.md
  docs/maintain-guides-how-to-validate-polkadot.md
  docs/maintain-guides-secure-validator.md
Labels: A0 - Please Review, T0 - Question

#2239 Update contributors.md
  docs/contributors.md
Labels: A1 - Do Not Merge

#2168 Clarify full nodes limitations
  docs/maintain-sync.md
Labels: A0 - Please Review

#2289 Update maintain-polkadot-parameters.md
  docs/learn-nominator.md
  docs/maintain-polkadot-parameters.md
Labels: A0 - Please Review

#2307 Update learn-account-generation.md
  docs/learn-account-generation.md
Labels: A3 - In Progress

#2349 [3] Issue Knock-off
  docs/build-cumulus.md
  docs/build-protocol-info.md
  docs/ens.md
  docs/kusama-adverserial-cheatsheet.md
  docs/learn-account-restore.md
  docs/learn-availability.md
  docs/learn-comparisons-cosmos.md
  docs/learn-comparisons.md
  docs/learn-ledger.md
  docs/learn-staking.md
  docs/maintain-errors.md
  docs/maintain-guides-how-to-join-council.md
  docs/maintain-guides-how-to-monitor-your-node.md
  docs/maintain-guides-how-to-nominate-kusama.md
  docs/maintain-guides-how-to-validate-kusama.md
  docs/maintain-sync.md
  docs/thousand-validators.md
Labels: A0 - Please Review

#2297 New Page: Runtime Upgrades
  docs/build-protocol-info.md
  docs/learn-runtime-upgrades.md
  website-v2/sidebars.js
  website/sidebars.json
Labels: K1 - Infrastructure, K5 - Learn, T2 - New Page

#2351 [CI] add staging server CICD and `prod` branch workflow
  .github/workflows/deploy-kusama-prod.yml
  .github/workflows/deploy-kusama-staging.yml
  .github/workflows/deploy-polkadot-prod.yml
  .github/workflows/deploy-polkadot-staging.yml
Labels: A0 - Please Review

#2364 Update docusaurus.config.js
  website-v2/docusaurus.config.js
Labels: A3 - In Progress

#2358 Update learn-accounts.md
  docs/learn-accounts.md
Labels: A0 - Please Review, A3 - In Progress, T3 - Enhancement

#2374 Page mirroring
  kusama-guide-v2/sidebars.js
Labels: P5 - Sometime Soon

#2361 Modify Secure Validator Setup
  docs/build-node-management.md
  docs/learn-validator.md
  docs/maintain-guides-how-to-use-polkadot-validator-setup.md
  docs/maintain-guides-secure-validator.md
  docs/maintain-index.md
  website-v2/sidebars.js
  website/sidebars.json
Labels: A0 - Please Review

#2367 Add Conditional Rendering for chain flag
  docs/maintain-sync.md
Labels: A0 - Please Review

#2375 Update maintain-guides-how-to-chill.md
  docs/learn-nominator.md
  docs/maintain-guides-how-to-chill.md
Labels: A0 - Please Review

#2384 Update sidebars.js
  docs/learn-video-tutorials.md
  website-v2/sidebars.js
Labels: A3 - In Progress

#1475 NGINX page added.
  docs/how-to-setup-a-validator-with-nginx-reverse-proxy.md
Labels: P5 - Sometime Soon, T2 - New Page
