Repository w3f/polkadot-wiki, pull requests merged in 2021-08, with the labels that each got.

#2403 Deprecate Fishermen
  docs/glossary.md
  docs/learn-availability.md
  docs/learn-randomness.md
Labels: A0 - Please Review

#2416 Update learn-accounts.md
  docs/learn-accounts.md
  website-v2/docusaurus.config.js
Labels: A3 - In Progress, P5 - Sometime Soon, T1 - Error :warning:

#2434 [WIP] Link new registrar, adjust outdated information
  docs/assets/identity/14.jpg
  docs/learn-identity.md
  docs/learn-registrar.md
Labels: A3 - In Progress, A1 - Do Not Merge :no_entry_sign:

#2424 Address changer and Client side redirects
  docs/learn-accounts.md
Labels: A1 - Do Not Merge :no_entry_sign:

#2444 update current contributors
  docs/general/contributors.md
Labels: A0 - Please Review

#2446 Resolves #2393
  docs/learn/learn-nominator.md
Labels: A0 - Please Review

#2465 Update Glossary Page with Edits & Add Additional Terms
  docs/glossary.md
Labels: A0 - Please Review

#2488 Add treasury-funded wallets
  docs/build/build-wallets.md
Labels: A1 - Do Not Merge :no_entry_sign:

#2510 fix build and maintain homepage links
  polkadot-wiki/src/pages/index.js
Labels: T1 - Bug :warning:
