Repository w3f/polkadot-wiki, pull requests merged in 2022-09, with the labels that each got.

#3731 Internationalization readme update
  README.md
  docs/general/contributing.md
Labels: A2 - Please Review

#3734 Remove Ambiguity on Staking Rewards calculation
  docs/learn/learn-staking.md
Labels: A2 - Please Review

#3760 Added Filippo description to contributors
  docs/general/contributors.md
Labels: A2 - Please Review

#3766 Swap resized imagery on Polkadot Getting-Started doc
  docs/general/getting-started.md
  docs/general/kusama/kusama-getting-started.md
  kusama-guide/static/img/kusama-guide/Account.jpg
  kusama-guide/static/img/kusama-guide/Account.png
  kusama-guide/static/img/kusama-guide/Ambassadors.jpg
  kusama-guide/static/img/kusama-guide/Ambassadors.png
  kusama-guide/static/img/kusama-guide/Bridges.jpg
  kusama-guide/static/img/kusama-guide/Bridges.png
  kusama-guide/static/img/kusama-guide/Council.jpg
  kusama-guide/static/img/kusama-guide/Council.png
  kusama-guide/static/img/kusama-guide/Identity.jpg
  kusama-guide/static/img/kusama-guide/Identity.png
  kusama-guide/static/img/kusama-guide/Parachain.jpg
  kusama-guide/static/img/kusama-guide/Parachain.png
  kusama-guide/static/img/kusama-guide/Proposal.jpg
  kusama-guide/static/img/kusama-guide/Proposal.png
  kusama-guide/static/img/kusama-guide/Proxy.jpg
  kusama-guide/static/img/kusama-guide/Proxy.png
  kusama-guide/static/img/kusama-guide/Stake.jpg
  kusama-guide/static/img/kusama-guide/Stake.png
  kusama-guide/static/img/kusama-guide/Transfer.jpg
  kusama-guide/static/img/kusama-guide/Transfer.png
  kusama-guide/static/img/kusama-guide/Treasury.jpg
  kusama-guide/static/img/kusama-guide/Treasury.png
  kusama-guide/static/img/kusama-guide/Voting.jpg
  kusama-guide/static/img/kusama-guide/Voting.png
  polkadot-wiki/static/img/polkadot-guide/Account.jpg
  polkadot-wiki/static/img/polkadot-guide/Account.png
  polkadot-wiki/static/img/polkadot-guide/Ambassadors.jpg
  polkadot-wiki/static/img/polkadot-guide/Ambassadors.png
  polkadot-wiki/static/img/polkadot-guide/Bridges.jpg
  polkadot-wiki/static/img/polkadot-guide/Bridges.png
  polkadot-wiki/static/img/polkadot-guide/Council.jpg
  polkadot-wiki/static/img/polkadot-guide/Council.png
  polkadot-wiki/static/img/polkadot-guide/Identity.jpg
  polkadot-wiki/static/img/polkadot-guide/Identity.png
  polkadot-wiki/static/img/polkadot-guide/Parachain.jpg
  polkadot-wiki/static/img/polkadot-guide/Parachain.png
  polkadot-wiki/static/img/polkadot-guide/Proposal.jpg
  polkadot-wiki/static/img/polkadot-guide/Proposal.png
  polkadot-wiki/static/img/polkadot-guide/Proxy.jpg
  polkadot-wiki/static/img/polkadot-guide/Proxy.png
  polkadot-wiki/static/img/polkadot-guide/Stake.jpg
  polkadot-wiki/static/img/polkadot-guide/Stake.png
  polkadot-wiki/static/img/polkadot-guide/Transfer.jpg
  polkadot-wiki/static/img/polkadot-guide/Transfer.png
  polkadot-wiki/static/img/polkadot-guide/Treasury.jpg
  polkadot-wiki/static/img/polkadot-guide/Treasury.png
  polkadot-wiki/static/img/polkadot-guide/Voting.jpg
  polkadot-wiki/static/img/polkadot-guide/Voting.png
Labels: A2 - Please Review

#3754 Multisig cancel transaction
  docs/learn/learn-accounts.md
Labels: A2 - Please Review

#3780 Fix MaxNominators variable refs in Nominator doc
  docs/learn/learn-nominator.md
Labels: A2 - Please Review

#3732 Apply prettier formatting to all docs containing RPC components ensuring rendering format is maintained
  README.md
  docs/general/faq.md
  docs/general/glossary.md
  docs/general/kusama/kusama-ledger.md
  docs/general/kusama/kusama-parameters.md
  docs/general/kusama/kusama-statemine.md
  docs/learn/learn-balance-transfers.md
  docs/learn/learn-crowdloans.md
  docs/learn/learn-governance.md
  docs/learn/learn-identity.md
  docs/learn/learn-nomination-pools.md
  docs/learn/learn-nominator.md
  docs/learn/learn-proxies.md
  docs/learn/learn-staking.md
  docs/learn/learn-statemint.md
  docs/learn/learn-treasury.md
  docs/maintain/kusama/maintain-guides-how-to-nominate-kusama.md
  docs/maintain/maintain-guides-how-to-nominate-polkadot.md
  docs/maintain/maintain-guides-how-to-validate-polkadot.md
  docs/maintain/maintain-guides-how-to-vote-councillor.md
  docs/maintain/maintain-polkadot-parameters.md
Labels: A2 - Please Review

#3779 Add section about Substrate connect
  docs/maintain/maintain-endpoints.md
Labels: A2 - Please Review

#3781 Update Delegate Voting section
  docs/assets/democracy/delegate-vote.png
  docs/assets/democracy/manage-delegation.png
  docs/assets/democracy/query-delegation.png
  docs/assets/democracy/undelegate-save.png
  docs/maintain/maintain-guides-democracy.md
Labels: A2 - Please Review

#3752 Xcm v2 updates
  docs/assets/cross-consensus/xcm-asset-teleportation 2.png
  docs/assets/cross-consensus/xcm-asset-teleportation.png
  docs/assets/cross-consensus/xcm-reserve-asset-transfer 2.png
  docs/assets/cross-consensus/xcm-reserve-asset-transfer.png
  docs/build/build-guide.md
  docs/build/build-hrmp-channels.md
  docs/build/build-parachains.md
  docs/build/build-storage.md
  docs/general/getting-started.md
  docs/learn/learn-DOT.md
  docs/learn/learn-architecture.md
  docs/learn/learn-bridges.md
  docs/learn/learn-collator.md
  docs/learn/learn-comparison-ethereum-2.md
  docs/learn/learn-comparisons-cosmos.md
  docs/learn/learn-cross-consensus.md
  docs/learn/learn-launch.md
  docs/learn/learn-nft.md
  docs/learn/learn-parachains.md
  docs/learn/learn-parathreads.md
  docs/learn/learn-spree.md
  docs/learn/learn-staking.md
  docs/learn/learn-teleport.md
  docs/learn/learn-transaction-fees.md
  docs/learn/learn-xcm.md
  polkadot-wiki/docusaurus.config.js
  polkadot-wiki/sidebars.js
Labels: A2 - Please Review

#3797 Use on-chain values via RPC for deposit base/factor table
  docs/learn/learn-accounts.md
Labels: A2 - Please Review

#3794 Update prettier configuration and restore running prettier on pre-commit hooks
  .github/ISSUE_TEMPLATE/feature-request.md
  .husky/pre-commit
  .prettierignore
  .prettierrc
  CODE_OF_CONDUCT.md
  README.md
Labels: A2 - Please Review

#3787 Staking Page Reorg
  docs/assets/staking/reward-risk.png
  docs/assets/staking/stash-controller.png
  docs/assets/staking/stash-stakingProxy.png
  docs/learn/learn-staking-advanced.md
  docs/learn/learn-staking.md
  kusama-guide/sidebars.js
  polkadot-wiki/sidebars.js
Labels: A1 - In Progress, A2 - Please Review

#3818 Staking Page - Minor fixes and Styling
  docs/learn/learn-staking-advanced.md
  docs/learn/learn-staking.md
Labels: A2 - Please Review

#3811 WIP: Sub0 banner
  polkadot-wiki/src/hooks/useScroll.js
  polkadot-wiki/src/pages/index.js
  polkadot-wiki/static/css/custom.css
Labels: A0 - Do Not Merge

#3800 Update third-party supported wallets section
  docs/build/build-wallets.md
Labels: A2 - Please Review

#3833 Reorg Assets Page
  docs/learn/learn-assets.md
Labels: A2 - Please Review

#3839 Ensure import statements are not impacted by prettier and are consistently terminated
  docs/general/kusama/kusama-ledger.md
  docs/general/kusama/kusama-parameters.md
  docs/general/kusama/kusama-statemine.md
  docs/learn/learn-governance.md
  docs/learn/learn-staking-advanced.md
  docs/maintain/kusama/maintain-guides-how-to-nominate-kusama.md
  docs/maintain/maintain-guides-how-to-validate-polkadot.md
Labels: A2 - Please Review

#3825 Reorg accounts page and migration to Advanced
  docs/assets/account-balance-types.png
  docs/learn/learn-account-advanced.md
  docs/learn/learn-account-generation.md
  docs/learn/learn-account-multisig.md
  docs/learn/learn-accounts.md
  polkadot-wiki/sidebars.js
Labels: A2 - Please Review

#3850 Minor edits to Intro to Staking
  docs/learn/learn-staking.md
Labels: A2 - Please Review

#3844 Add links to Polkadot Staking page and Dashboard
  docs/learn/learn-nominator.md
  docs/learn/learn-staking-advanced.md
  docs/learn/learn-staking.md
Labels: A2 - Please Review

#3854 Update bagsList to voterList
  docs/learn/learn-nominator.md
  docs/learn/learn-staking-advanced.md
Labels: A2 - Please Review

#3841 Reorg DOT page
  docs/learn/learn-DOT.md
Labels: A3 - Changes Requested
