Repository w3f/polkadot-wiki, pull requests merged in 2022-04, with the labels that each got.

#3162 Add Admonitions to General Docs
  docs/general/claims.md
  docs/general/community.md
  docs/general/contributing.md
  docs/general/ens.md
  docs/general/faq.md
  docs/general/getting-started.md
  docs/general/glossary.md
  docs/general/grants.md
  docs/general/redenomination.md
  docs/general/scams.md
  docs/general/thousand-validators.md
Labels: A2 - Please Review

#3174 Add references for bagsList.putInFrontOf to Staking FAQ doc
  docs/learn/learn-staking-faq.md
Labels: A3 - Changes Requested

#3194 Update Video Tutorials Doc
  docs/learn/learn-video-tutorials.md
Labels: A2 - Please Review

#3187 Update Kusama Max Nominations
  docs/general/kusama/kusama-parameters.md
  docs/maintain/kusama/maintain-guides-how-to-nominate-kusama.md
  docs/maintain/maintain-guides-how-to-nominate-polkadot.md
  docs/maintain/maintain-polkadot-parameters.md
  scripts/inject-dict.json
Labels: A2 - Please Review

#3168 General Updates to Contributors Page
  docs/general/contributors.md
Labels: A2 - Please Review

#3244 Add Algolia Config & Update Dependencies
  kusama-guide/docusaurus.config.js
  package.json
  polkadot-wiki/docusaurus.config.js
  yarn.lock
Labels: dependencies
