Repository w3f/polkadot-wiki, pull requests merged in 2022-03, with the labels that each got.

#3052 Add General Tools page and Block Time Estimator
  docs/general/tools.mdx
  polkadot-wiki/docusaurus.config.js
  polkadot-wiki/sidebars.js
  polkadot-wiki/src/components/BlockHeightEstimator.tsx
  polkadot-wiki/static/js/blockHeightEstimator.ts
Labels: 1KC

#3061 Add Web3Go to Data Analytics
  docs/build/build-data.md
Labels: A3 - Changes Requested

#3107 Setting sub-identities using Ledger
  docs/assets/identity/sub-id-1.png
  docs/assets/identity/sub-id-2.png
  docs/assets/identity/sub-id-3.png
  docs/general/kusama/kusama-ledger.md
  docs/learn/learn-identity.md
  docs/maintain/maintain-guides-validator-community.md
Labels: A2 - Please Review

#3129 Staking Terminology for Nominators
  docs/assets/staking/nominator-election.png
  docs/general/getting-started.md
  docs/learn/learn-nominator.md
  docs/learn/learn-staking.md
  docs/maintain/maintain-polkadot-parameters.md
Labels: A2 - Please Review
