Repository w3f/polkadot-wiki, pull requests merged in 2022-08, with the labels that each got.

#3581 Remove how to guides - Identity
  docs/learn/learn-identity.md
Labels: A2 - Please Review

#3596 Clean up Grants page and refs
  docs/build/build-index.md
  docs/general/grants.md
Labels: A2 - Please Review

#3582 Add Tools section - Blockchain Analytics
  docs/build/build-tools-index.md
Labels: A2 - Please Review

#3584 Move Polkadot Open Stack doc to the Wiki from Grants repo
  .github/workflows/status-badges.yml
  README.md
  docs/build/build-open-source.md
  kusama-guide/sidebars.js
  polkadot-wiki/sidebars.js
Labels: A2 - Please Review

#3595 Add Preimage to Glossary
  docs/general/glossary.md
Labels: A2 - Please Review

#3601 Update for issue #3600
  docs/general/ledger.md
Labels: A2 - Please Review

#3357 Staking miner
  docs/assets/staking-miner/NPoS-election-optimization.png
  docs/learn/learn-staking-miner.md
  polkadot-wiki/sidebars.js
Labels: A2 - Please Review

#3564 Update reference hardware
  docs/maintain/kusama/maintain-guides-how-to-validate-kusama.md
  docs/maintain/maintain-guides-how-to-validate-polkadot.md
Labels: A2 - Please Review

#3621 Adding ONE-T to the open source stack
  docs/build/build-open-source.md
Labels: A2 - Please Review

#3617 Fix broken links on open stack doc
  docs/build/build-open-source.md
Labels: A2 - Please Review

#3628 Add AlephBFT finality gadget.
  docs/build/build-open-source.md
Labels: A2 - Please Review

#3627 Update Polkadot Stack
  docs/build/build-open-source.md
Labels: A2 - Please Review

#3633 Link to Open Stack on Community page
  docs/general/community.md
Labels: A2 - Please Review

#3626 Add minStake info for Validators
  components/Minimum-Stake.jsx
  components/RPC-Connection.jsx
  components/utilities/filters.js
  docs/maintain/maintain-guides-how-to-validate-polkadot.md
Labels: A2 - Please Review

#3635 Min stake clarification
  components/Minimum-Stake.jsx
Labels: A2 - Please Review

#3642 Remove Staging build CI for PRs
  .github/workflows/deploy-kusama-staging.yml
  .github/workflows/deploy-polkadot-staging.yml
Labels: A2 - Please Review

#3594 Parachain Lease Extension Explained
  docs/assets/para-swap.png
  docs/learn/learn-auction.md
Labels: A2 - Please Review

#3666 Update refs to Max Validators in Active set
  docs/learn/learn-staking.md
Labels: A2 - Please Review

#3665 Reorg nomination pools
  docs/learn/learn-nomination-pools.md
Labels: A2 - Please Review

#3676 Migration of account generation page to support pages
  docs/learn/learn-account-generation.md
Labels: A3 - Changes Requested

#3692 Add workflow_dispatch trigger for Polkadot & Kusama staging build actions
  .github/workflows/deploy-kusama-staging.yml
  .github/workflows/deploy-polkadot-staging.yml
Labels: A2 - Please Review

#3696 Added tip link & reorg tipping example
  docs/learn/learn-treasury.md
Labels: A2 - Please Review

#3691 Added password derivation
  docs/learn/learn-accounts.md
Labels: A3 - Changes Requested

#3698 Remove migrated support content for statemine/statemint
  docs/assets/statemint/Statemint-asset-transfer-1.png
  docs/assets/statemint/Statemint-asset-transfer-2.png
  docs/assets/statemint/Statemint-asset-transfer-3.png
  docs/general/kusama/kusama-statemine.md
  docs/learn/learn-statemint.md
Labels: A1 - In Progress

#3699 Remove migrated support content teleporting
  docs/assets/Teleport-DOT-Statemint.png
  docs/assets/kusama/KSM-Teleport-Kusama.png
  docs/assets/kusama/KSM-teleport-small.png
  docs/assets/kusama/ksm-teleport-apps.png
  docs/assets/statemint/Statemint-Teleport-1.png
  docs/assets/statemint/Statemint-Teleport-2.png
  docs/assets/statemint/Statemint-Teleport-3.png
  docs/learn/learn-teleport.md
Labels: A2 - Please Review

#3706 Remove migrated support content for Polkadot Claims
  docs/assets/new-claims/claim-1.jpg
  docs/assets/new-claims/claim-10.jpg
  docs/assets/new-claims/claim-2-1.jpg
  docs/assets/new-claims/claim-2.jpg
  docs/assets/new-claims/claim-3.png
  docs/assets/new-claims/claim-4.png
  docs/assets/new-claims/claim-5.png
  docs/assets/new-claims/claim-6.png
  docs/assets/new-claims/claim-7.jpg
  docs/assets/new-claims/claim-8.jpg
  docs/assets/new-claims/claim-9.jpg
  docs/assets/new-claims/claim-attest-1.png
  docs/assets/new-claims/claim-attest-2.png
  docs/assets/new-claims/claim-attest-3.png
  docs/assets/new-claims/claim-attest-4.png
  docs/assets/new-claims/new-attest-1.jpg
  docs/assets/new-claims/new-attest-2.png
  docs/assets/new-claims/new-attest-3.jpg
  docs/assets/new-claims/new-attest-4.jpg
  docs/assets/new-claims/new-attest-5.jpg
  docs/assets/new-claims/new-claim-2.png
  docs/assets/new-claims/new-claim-5.png
  docs/assets/new-claims/new-claim-6.png
  docs/assets/new-claims/new-claim-7.png
  docs/assets/new-claims/ps-01.jpg
  docs/assets/new-claims/ps-02.jpg
  docs/assets/new-claims/ps-03.jpg
  docs/assets/new-claims/ps-3r.jpg
  docs/assets/new-claims/ps-claim-1.jpg
  docs/assets/new-claims/ps-claim-2.png
  docs/assets/new-claims/ps-claim-3.png
  docs/assets/new-claims/ps-claim-5.png
  docs/assets/new-claims/ps-claim-6.png
  docs/assets/new-claims/ps-claim-7.png
  docs/assets/new-claims/ps-claim-8.png
  docs/general/claims.md
Labels: A2 - Please Review

#3707 Remove migrated support content for Proxy & Anonymous Proxy Account creation
  docs/assets/polkadot_add_another_proxy.png
  docs/assets/polkadot_anon_proxy.png
  docs/assets/polkadot_generating_proxy.png
  docs/learn/learn-proxies.md
Labels: A2 - Please Review

#3709 Recovery pallet on Kusama, Absent on Polkadot
  docs/learn/learn-balance-transfers.md
Labels: A2 - Please Review

#3695 Partial migration of identity page
  docs/learn/learn-identity.md
Labels: A2 - Please Review

#3723 Update migrated support content for Comparing Polkadot and Kusama
  docs/learn/learn-kusama-vs-polkadot.md
Labels: A2 - Please Review

#3715 Update migrated support content for Parachain Slots Auction
  docs/learn/learn-auction.md
Labels: A2 - Please Review

#3728 Encointer update
  docs/learn/learn-common-good-chains.md
Labels: A3 - Changes Requested

#3730 Restored in-text links for Ledger page
  docs/general/ledger.md
Labels: A1 - In Progress, A2 - Please Review
