Repository w3f/polkadot-wiki, pull requests merged in 2023-01, with the labels that each got.

#4262 System > Common Good Parachains
  docs/build/build-hrmp-channels.md
  docs/build/build-parachains.md
  docs/general/glossary.md
  docs/general/kusama/kusama-statemine-ledger.md
  docs/general/kusama/kusama-statemine.md
  docs/learn/learn-assets.md
  docs/learn/learn-common-good-chains.md
  docs/learn/learn-nft.md
  docs/learn/learn-parachains.md
  docs/learn/learn-statemint.md
  docs/learn/learn-system-chains.md
  polkadot-wiki/docusaurus.config.js
  polkadot-wiki/sidebars.js
Labels: K3 - Parachains, A2 - Please Review

#4248 Added details for the slash of era 4543 on Kusama
  docs/maintain/maintain-guides-best-practices-to-avoid-slashes.md
Labels: A2 - Please Review

#4264 Add new definitions to glossary & replace Gov2 with OpenGov
  docs/general/glossary.md
  docs/learn/learn-governance.md
  docs/learn/learn-opengov.md
Labels: A2 - Please Review

#4223 Rewrite of the Secure Websocket explanation
  docs/maintain/maintain-guides-how-to-validate-polkadot.md
  docs/maintain/maintain-wss.md
Labels: A2 - Please Review

#4289 Fix redirects - OpenGov
  kusama-guide/docusaurus.config.js
  kusama-guide/sidebars.js
  polkadot-wiki/docusaurus.config.js
Labels: A2 - Please Review

#4271 Update and restore Kusama auction tool automated cache
  components/Auction-Schedule.jsx
  components/utilities/data/KusamaAuctions.json
  components/utilities/data/PolkadotAuctions.json
Labels: A2 - Please Review

#4263 Additional information on system chains and collectives
  docs/learn/learn-system-chains.md
  polkadot-wiki/docusaurus.config.js
Labels: A2 - Please Review

#4301 Add max number of proxies to learn proxies
  docs/learn/learn-proxies.md
Labels: A2 - Please Review

#4302 Add new component for displaying current fellowship members and ranks from on-chain data
  components/Fellowship.jsx
  docs/learn/learn-opengov.md
Labels: A2 - Please Review

#4316 Remove outdated info - Staking Election
  docs/learn/learn-phragmen.md
Labels: A2 - Please Review

#4321 Fix broken RPC paths
  docs/general/glossary.md
  docs/learn/learn-accounts.md
  docs/learn/learn-nominator.md
  docs/learn/learn-staking-advanced.md
  docs/maintain/maintain-guides-how-to-nominate-polkadot.md
  docs/maintain/maintain-guides-validator-payout.md
Labels: A2 - Please Review

#4325 Update Chill Other section
  docs/maintain/maintain-guides-how-to-chill.md
Labels: A2 - Please Review

#4323 Create new RPC tests for all active paths
  docs/learn/learn-account-multisig.md
  docs/learn/learn-staking.md
  tests/rpc.test.js
Labels: A2 - Please Review

#4329 Update info on Staking page - Nomination pools
  docs/learn/learn-nomination-pools.md
  docs/learn/learn-staking.md
  tests/rpc.test.js
Labels: A2 - Please Review

#4331 ConvictionVoting lock removal instructions
  docs/maintain/maintain-guides-opengov.md
Labels: A2 - Please Review

#4332 Polish Account Generation doc and add info about Account creation on the UI
  docs/learn/learn-account-generation.md
Labels: A2 - Please Review

#4334 Remove unused dependencies
  kusama-guide/docusaurus.config.js
  package.json
  polkadot-wiki/docusaurus.config.js
  yarn.lock
Labels: A2 - Please Review

#4336 Remove unused dependencies - updated
  kusama-guide/docusaurus.config.js
  package.json
  polkadot-wiki/docusaurus.config.js
  yarn.lock
Labels: A1 - In Progress

#4333 Add new GitHub action for deploying docs to prod every 24 hrs
  .github/workflows/update-prod.yml
Labels: A2 - Please Review

#4190 Add troubleshooting info about staking rewards
  docs/learn/learn-staking.md
Labels: A2 - Please Review

#4339 Calls and Pallets accessed by Proxies
  docs/learn/learn-proxies.md
Labels: A2 - Please Review

#4122 Create new page about Parachains' Protocol Overview
  docs/assets/parachain-approval-process.png
  docs/assets/parachain-forks.png
  docs/assets/parachain-inclusion-pipeline.png
  docs/assets/parachain-protocol-summary.png
  docs/learn/learn-parachains-protocol.md
  polkadot-wiki/sidebars.js
Labels: A2 - Please Review, epic

#4355 Consolidate auto deploy jobs
  .github/workflows/deploy-kusama-prod.yml
  .github/workflows/deploy-polkadot-prod.yml
  .github/workflows/update-prod.yml
Labels: A2 - Please Review

#4352 Update min nomination bond
  docs/general/getting-started.md
  docs/learn/learn-nominator.md
Labels: A2 - Please Review

#4361 Address edge condition where auction updating process fails to terminate
  components/utilities/getAuctions.js
Labels: A2 - Please Review

#4362 Remove IPFS package from repo
  README.md
  package.json
Labels: A2 - Please Review

#4391 Add Motion to glossary
  docs/general/glossary.md
Labels: A2 - Please Review

#4384 Staging Deployment - Manual run
  .github/workflows/deploy-kusama-staging.yml
  .github/workflows/deploy-polkadot-staging.yml
Labels: A2 - Please Review

#4378 Add React component for visualizing origins and tracks for OpenGov
  components/Referenda-Tracks.jsx
  docs/learn/learn-opengov.md
  docs/maintain/maintain-guides-opengov.md
Labels: A2 - Please Review

#4404 Add GitHub Action details for all automation jobs to README table
  README.md
Labels: A2 - Please Review
