Repository w3f/polkadot-wiki, pull requests merged in 2023-11, with the labels that each got.

#5307 Add Bounty Context to Treasury Page
  docs/learn/learn-bridges.md
  docs/learn/learn-guides-bounties.md
  docs/learn/learn-polkadot-opengov-treasury.md
  docs/maintain/maintain-guides-async-backing.md
Labels: A2 - Please Review, A0 - Do Not Merge

#5340 Edit Polkadot JS sections Pt. 1
  docs/general/governance-apps.md
  docs/general/how-to-dyor.md
  docs/general/ledger.md
  docs/general/metadata.md
  docs/general/multisig-apps.md
  docs/general/polkadot-vault.md
  docs/general/polkadotjs.md
  docs/general/staking-apps.md
  docs/general/staking-dashboard.md
  docs/learn/learn-account-advanced.md
  docs/learn/learn-guides-assets-create.md
  docs/learn/learn-guides-assets-ledger.md
  docs/learn/learn-guides-bounties.md
  docs/learn/learn-guides-identity.md
  docs/learn/learn-guides-ledger.md
  docs/learn/learn-guides-polkadot-opengov.md
  docs/learn/learn-guides-staking-pools.md
  docs/learn/learn-guides-staking.md
  docs/learn/learn-guides-treasury.md
  docs/learn/learn-guides-vault.md
  polkadot-wiki/sidebars.js
Labels: A2 - Please Review, A0 - Do Not Merge

#5332 Build Section Reorg - "Polkadot Developer Portal"
  docs/build/build-dapp.md
  docs/build/build-data.md
  docs/build/build-guide.md
  docs/build/build-light-clients.md
  docs/build/build-network-overview.md
  docs/build/build-protocol-info.md
  docs/build/build-ss58-registry.md
  docs/general/polkadot-direction.md
  docs/general/staking-dashboard.md
  docs/general/web3-and-polkadot.md
  kusama-guide/sidebars.js
  polkadot-wiki/docusaurus.config.js
  polkadot-wiki/sidebars.js
  polkadot-wiki/src/pages/index.js
Labels: A2 - Please Review

#5358 Edit registrar fees
  docs/learn/learn-identity.md
Labels: A2 - Please Review

#5364 Improve descriptions
  polkadot-wiki/sidebars.js
Labels: A2 - Please Review

#5369 Edit Convictions Polkadot
  components/Voluntary-Locking.jsx
  docs/learn/learn-polkadot-opengov.md
Labels: A2 - Please Review

#5368 Fix delegation info
  docs/learn/learn-polkadot-opengov.md
Labels: A2 - Please Review

#5371 Add info RFC
  docs/general/start-building.md
Labels: A2 - Please Review

#5389 Fix broken links xcm pages
  docs/learn/xcm/fundamentals/weight_and_fees.md
  docs/learn/xcm/journey/transact.md
Labels: A1 - In Progress

#5390 Add info proxies
  docs/learn/learn-proxies.md
Labels: A2 - Please Review

#5394 Minor fix - Kusama Guide Sidebar
  kusama-guide/sidebars.js
Labels: A2 - Please Review
