Repository w3f/polkadot-wiki, pull requests merged in 2024-01, with the labels that each got.

#5453 Add hyperlink to metadata extrinsic description
  components/Metadata.jsx
Labels: A2 - Please Review

#5463 Add jobs board and PBA info
  docs/general/community.md
Labels: A2 - Please Review

#5462 Use the right term - Manifesto for Fellowhip
  docs/learn/learn-polkadot-opengov.md
Labels: A2 - Please Review

#5425 Remove Polkadot JS mentions from Section Transactions
  docs/general/community.md
  docs/general/how-to-dyor.md
  docs/general/polkadot-direction.md
  docs/general/polkadot-v1.md
  docs/general/polkadot-vault.md
  docs/general/polkadotjs-ui.md
  docs/general/polkadotjs.md
  docs/general/staking-dashboard.md
  docs/general/transaction-attacks.md
  docs/learn/learn-DOT.md
  docs/learn/learn-account-abstraction.md
  docs/learn/learn-account-advanced.md
  docs/learn/learn-accounts.md
  docs/learn/learn-extrinsics.md
  docs/learn/learn-guides-accounts.md
  docs/learn/learn-guides-assets-ledger.md
  docs/learn/learn-guides-ledger.md
  docs/learn/learn-guides-transfers.md
  docs/learn/learn-guides-vault.md
  docs/learn/learn-inflation.md
  docs/learn/learn-nft-pallets.md
  docs/learn/learn-parachains.md
  docs/learn/learn-polkadot-js-guides.md
  docs/learn/learn-polkadot-opengov.md
  docs/learn/learn-proxies.md
  docs/learn/learn-staking-advanced.md
  docs/learn/learn-transaction-fees.md
  docs/learn/learn-transactions.md
  kusama-guide/sidebars.js
  polkadot-wiki/docusaurus.config.js
  polkadot-wiki/sidebars.js
Labels: A2 - Please Review

#5484 Add Polkassembly as Kusama Registrar
  docs/learn/learn-identity.md
Labels: A2 - Please Review

#5479 Update Inflation Page
  docs/assets/NPoS/staking-rate-with-parachains.png
  docs/assets/rewards-inflation.png
  docs/learn/learn-inflation.md
Labels: A2 - Please Review

#5486 Update Kusama Guide Sidebar
  kusama-guide/sidebars.js
Labels: A2 - Please Review

#5487 Fix broken links Getting Started Cards
  docs/general/getting-started.md
  docs/general/kusama/kusama-getting-started.md
Labels: A1 - In Progress

#5493 Fix Staking API Max Nominations
  docs/general/kusama/kusama-parameters.md
  docs/learn/learn-nominator.md
  docs/learn/learn-phragmen.md
  docs/learn/learn-staking.md
  docs/maintain/kusama/maintain-guides-how-to-nominate-kusama.md
  docs/maintain/maintain-polkadot-parameters.md
Labels: A2 - Please Review

#5497 Hardcoded Values for deprecated pallets
  docs/learn/learn-governance.md
  docs/learn/learn-treasury.md
Labels: A2 - Please Review

#5501 Minor Update - link to active issuance
  docs/learn/learn-polkadot-opengov.md
Labels: A2 - Please Review

#5500 Update General admin description
  docs/learn/learn-polkadot-opengov-origins.md
Labels: A2 - Please Review

#5510 Banner Grants Programme
  docs/general/grants.md
Labels: A2 - Please Review

#5512 Modify Design Cards
  docs/general/getting-started.md
  docs/general/governance-apps.md
  docs/general/polkadot-vault.md
  docs/general/scams.md
  docs/general/staking-apps.md
  docs/learn/learn-DOT.md
  docs/learn/learn-architecture.md
  docs/learn/learn-auction.md
  docs/learn/learn-crowdloans.md
  docs/learn/learn-guides-accounts-proxy.md
  docs/learn/learn-guides-accounts.md
  docs/learn/learn-guides-bounties.md
  docs/learn/learn-nft-projects.md
  docs/learn/learn-polkadot-opengov.md
  docs/learn/learn-video-tutorials.md
  docs/learn/learn-xcm-transport.md
Labels: A2 - Please Review, A0 - Do Not Merge

#5513 Refine OpenGov doc
  docs/learn/learn-polkadot-opengov.md
Labels: A2 - Please Review

#5507 Update learn-hyperbridge.md
  docs/learn/learn-hyperbridge.md
Labels: A2 - Please Review, Community PR

#5527 1KV program on hold - info note
  docs/general/thousand-validators.md
Labels: A2 - Please Review

#5530 Clarify Multi-sig call deposits
  docs/learn/learn-guides-accounts-multisig.md
Labels: A2 - Please Review

#5521 Edits Hyperbridge
  docs/learn/learn-hyperbridge.md
Labels: A2 - Please Review

#5531 Add info transactions
  docs/general/transaction-attacks.md
  docs/learn/learn-transactions.md
Labels: A2 - Please Review

#5499 Update Fellowship Membership instructions
  docs/assets/fellowship-add-member-preimage.png
  docs/assets/fellowship-add-member-proposal.png
  docs/assets/fellowship-candidate-proposal.png
  docs/assets/fellowship-induct-candidate.png
  docs/assets/fellowship-promote-member.png
  docs/assets/fellowship-promotion-proposal.png
  docs/assets/fellowship-whitelist-xcm.png
  docs/learn/learn-polkadot-opengov.md
  docs/learn/learn-polkadot-technical-fellowship.md
  polkadot-wiki/sidebars.js
Labels: A2 - Please Review

#5503 Add Polimec HRMP info
  docs/build/build-hrmp-channels.md
  docs/general/community.md
  docs/general/thousand-validators.md
  docs/learn/learn-guides-accounts-multisig.md
Labels: A2 - Please Review

#5535 Add Voting Locks section to OpenGov
  docs/learn/learn-polkadot-opengov.md
Labels: A2 - Please Review

#5556 Add info account balances
  docs/learn/learn-guides-accounts.md
Labels: A2 - Please Review

#5563 Fellowship Induction does not require a proposal
  docs/assets/fellowship-candidate-proposal.png
  docs/assets/fellowship-induct-call.png
  docs/assets/fellowship-induct-candidate.png
  docs/learn/learn-polkadot-technical-fellowship.md
Labels: A2 - Please Review
