Repository w3f/polkadot-wiki, pull requests merged in 2025-05, with the labels that each got.

#6658 [IA] Filter out pages from build / maintain
  docs/general/build-open-source.md
  docs/general/maintain-errors.md
  docs/learn/learn-transaction-construction.md
  mkdocs.yml
  scripts/_redirects
Labels: A2 - Please Review

#6661 Clean up guides section
  docs/kusama/kusama-getting-started.md
  docs/kusama/kusama-society.md
  docs/learn/learn-guides-accounts.md
  docs/learn/learn-guides-assets.md
  docs/learn/learn-guides-bridges.md
  docs/learn/learn-guides-nominator.md
  docs/learn/learn-guides-staking.md
  docs/learn/learn-polkadot-js-guides.md
  docs/learn/learn-staking.md
  docs/learn/maintain-guides-async-backing.md
  mkdocs.yml
  scripts/_redirects
Labels: A2 - Please Review

#6665 Remove old programs
  docs/general/dev-heroes.md
  docs/general/polkadot-v1.md
  docs/general/thousand-contributors.md
  mkdocs.yml
Labels: A2 - Please Review

#6668 Update glossary.md
  docs/general/glossary.md
Labels: A2 - Please Review

#6675 Remote proxy tool
  docs/learn/learn-proxies-pure.md
Labels: A2 - Please Review

#6662 Edit Comparisons
  docs/learn/learn-comparisons-rollups.md
Labels: A2 - Please Review

#6674 New IA
  docs/assets/Architecture.png
  docs/assets/Research.png
  docs/assets/apps.png
  docs/assets/collectives.png
  docs/assets/community.png
  docs/assets/comparisons.png
  docs/assets/decentralized-computer.png
  docs/assets/explore/Polkadot OpenGov 2.png
  docs/assets/explore/Set an Identity 2.png
  docs/assets/future-vision.png
  docs/assets/kusama.png
  docs/assets/nfts.png
  docs/assets/polkadot-hub.png
  docs/assets/stay-safe.png
  docs/assets/vision.png
  docs/assets/wallets.png
  docs/general/fundamentals.md
  docs/general/nft-projects.md
  docs/index.md
  docs/learn/learn-architecture.md
  material-overrides/architecture-cards.html
  material-overrides/explore-cards.html
  material-overrides/fundamentals-cards.html
  mkdocs.yml
Labels: A2 - Please Review

#6676 Add tooltips to Wiki
  includes/definitions.md
  mkdocs.yml
Labels: A2 - Please Review

#6677 Fix / Update Avalanche Comparison
  docs/learn/learn-comparisons-avalanche.md
Labels: A2 - Please Review

#6682 Merge JS guides content + edit home card
  docs/general/polkadotjs.md
  docs/index.md
  docs/learn/learn-polkadot-js-guides.md
  mkdocs.yml
  scripts/_redirects
Labels: A2 - Please Review

#6680 Add info of which extrinsics can be submitted in each OpenGov Track
  docs/learn/learn-polkadot-opengov-origins.md
Labels: A2 - Please Review

#6697 Fix Broken Redirects
  scripts/_redirects
Labels: A2 - Please Review

#6701 Add light client redirect
  scripts/_redirects
Labels: A2 - Please Review

#6688 Remove archived pages
  docs/general/dashboards/dune-analytics/polkadot-dashboards/legacy/polkadot-governance-dashboard.md
  docs/general/dashboards/dune-analytics/polkadot-dashboards/legacy/polkadot-opengov-referendum-voting-analysis.md
  docs/general/dashboards/dune-analytics/polkadot-dashboards/legacy/polkadot-staking-dashboard.md
  docs/general/dashboards/dune-analytics/polkadot-dashboards/polkadot-dashboards-governance.md
  docs/general/dashboards/dune-analytics/polkadot-dashboards/polkadot-dashboards-overview.md
  docs/general/faq.md
  docs/general/how-to-dyor.md
  docs/general/metadata.md
  docs/general/polkadot-direction.md
  docs/general/polkadot-v1.md
  docs/kusama/kusama-timeline.md
  docs/learn/archive/learn-auction.md
  docs/learn/archive/learn-controller.md
  docs/learn/archive/learn-crowdloans.md
  docs/learn/archive/learn-governance.md
  docs/learn/archive/learn-launch.md
  docs/learn/archive/learn-redenomination.md
  docs/learn/archive/learn-treasury.md
  docs/learn/archive/maintain-guides-democracy.md
  docs/learn/archive/maintain-guides-how-to-join-council.md
  docs/learn/archive/maintain-guides-how-to-vote-councillor.md
  docs/learn/archive/thousand-validators.md
  docs/learn/learn-DOT.md
  docs/learn/learn-agile-coretime.md
  docs/learn/learn-guides-coretime-parachains.md
  docs/learn/learn-hyperbridge.md
  docs/learn/learn-offenses.md
  docs/learn/learn-phragmen.md
  docs/learn/learn-polkadot-opengov.md
  docs/learn/learn-polkadot-technical-fellowship.md
  docs/learn/learn-safrole.md
  includes/definitions.md
  mkdocs.yml
  scripts/_redirects
Labels: A2 - Please Review

#6700 Landing page improvements
  docs/stylesheets/extra.css
Labels: A2 - Please Review

#6702 Contributing Guidelines
  docs/general/contributing.md
Labels: A1 - In Progress

#6705 Fix Links Audit Script
  Audit-Results.md
  docs/general/build-open-source.md
  docs/general/community.md
  docs/general/contributors.md
  docs/general/faq.md
  docs/general/getting-started.md
  docs/general/glossary.md
  docs/general/governance-apps.md
  docs/general/grants.md
  docs/general/pcf.md
  docs/general/polkadot-v1.md
  docs/general/scams.md
  docs/general/start-building.md
  docs/general/wallets-and-extensions.md
  docs/learn/learn-account-advanced.md
  docs/learn/learn-agile-coretime.md
  docs/learn/learn-async-backing.md
  docs/learn/learn-comparisons-cosmos.md
  docs/learn/learn-cryptography.md
  docs/learn/learn-guides-vault.md
  docs/learn/learn-hyperbridge.md
  docs/learn/learn-parachains-faq.md
  docs/learn/learn-polkadot-opengov.md
  docs/learn/learn-polkadot-technical-fellowship.md
  docs/learn/learn-proxies.md
  docs/learn/learn-staking.md
  docs/learn/learn-system-chains.md
  scripts/_redirects
  scripts/auditLinks.py
Labels: A2 - Please Review

#6713 Remove duplicated / unused pages
  docs/general/dashboards/staking-dashboard.md
  docs/general/ledger.md
  docs/general/polkadotjs-ui.md
  docs/general/polkadotjs.md
  docs/general/scams.md
  docs/general/staking-apps.md
  docs/general/wallets-and-extensions.md
  docs/learn/learn-account-advanced.md
  docs/learn/learn-accounts.md
  docs/learn/learn-comparison-ethereum.md
  docs/learn/learn-guides-bounties.md
  docs/learn/learn-guides-claims.md
  docs/learn/learn-implementations.md
  docs/learn/learn-parachains.md
  docs/learn/learn-polkadot-opengov.md
  docs/learn/learn-runtime-upgrades.md
  docs/learn/learn-spree.md
  docs/learn/learn-staking.md
  docs/learn/learn-wasm.md
  material-overrides/explore-cards.html
  mkdocs.yml
  scripts/_redirects
Labels: A2 - Please Review

#6718 Update Landing Page
  docs/index.md
  docs/javascript/init_kapa_widget.js
  docs/stylesheets/announcement-bar.css
  docs/stylesheets/extra.css
  material-overrides/assets/explore/Balance Transfers.png
  material-overrides/assets/explore/Become an Ambassador.png
  material-overrides/assets/explore/Bridges.png
  material-overrides/assets/explore/Creating an account.png
  material-overrides/assets/explore/Gift.png
  material-overrides/assets/explore/Parachains.png
  material-overrides/assets/explore/Polkadot OpenGov.png
  material-overrides/assets/explore/Proxy Accounts.png
  material-overrides/assets/explore/Set an Identity.png
  material-overrides/assets/explore/Staking.png
  material-overrides/assets/images/external_item.svg
  material-overrides/assets/images/favicon.webp
  material-overrides/assets/images/gradient.webp
  material-overrides/assets/images/home-card-1.webp
  material-overrides/assets/images/home-card-2.webp
  material-overrides/assets/images/logo.webp
  material-overrides/assets/images/wiki-logo-white-dark.svg
  material-overrides/assets/images/wiki-logo.svg
  material-overrides/assets/stylesheets/MessageBox.css
  material-overrides/assets/stylesheets/announcement-bar.css
  material-overrides/assets/stylesheets/extra.css
  material-overrides/assets/stylesheets/fonts/Unbounded-Regular.ttf
  material-overrides/assets/stylesheets/home.css
  material-overrides/assets/stylesheets/index-page.css
  material-overrides/assets/stylesheets/polkadot.css
  material-overrides/assets/stylesheets/terminal.css
  material-overrides/assets/stylesheets/timeline-neoteroi.css
  material-overrides/home.html
  material-overrides/js/MessageBox.js
  material-overrides/js/header-scroll.js
  material-overrides/js/root-level-sections.js
  material-overrides/js/search-bar-results.js
  material-overrides/js/simple-analytics.js
  material-overrides/main.html
  material-overrides/partials/footer.html
  material-overrides/partials/header.html
  material-overrides/partials/index-page.html
  material-overrides/partials/palette.html
  material-overrides/partials/root-subdirectory-page.html
  material-overrides/partials/search.html
  material-overrides/partials/source-file.html
  material-overrides/partials/tabs.html
  mkdocs.yml
Labels: A2 - Please Review, A0 - Do Not Merge
